Add `emath::Number` compatibility
JonathanWoollett-Light/ux2 pull request #30
Opened 2024-02-02 01:43 UTC by C0D3-M4513R

### Summary of the PR

*Please summarize here why the changes in this PR are needed.*

To Construct a `egui::DragValue` the type needs to implement `emath::Number`.
This pr adds a feature to add a `emath::Number` implementation.

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [ ] All added/changed functionality has a corresponding unit/integration
  test.
- [x] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

2024-02-02 01:47 UTC, C0D3-M4513R commented
> All added/changed functionality has a corresponding unit/integration
test.

I'm sorry what unit/integration tests?

2024-02-11 00:23 UTC, JonathanWoollett-Light commented
Apologies for delay on reviewing, I've been quite busy lately, I will try to get to this in the next week.

2024-02-11 00:50 UTC, C0D3-M4513R commented
uhm sorry, some commits leaked from a rewrite I attempted.
Also I only implemented the changes for unsigned types I realised.
The proc_macro code is quite unreadable to me, so I apologise.

2024-03-04 22:05 UTC, JonathanWoollett-Light requested changes
For the `emath` change please squash all changes into 1 commit, entitled `` feat: Add `emath::number` ``, you do not need to change the changelog or readme, this will be done automatically by CI.

The other changes like `Add no_std support` should be in a separate PR.

2024-03-04 22:05 UTC, JonathanWoollett-Light commented on ux2-macros/src/lib.rs
> +            #[cfg(feature = "emath")]
Please add a newline here.

2024-03-04 22:05 UTC, JonathanWoollett-Light commented on ux2-macros/src/lib.rs
> +            }
Please add a newline here.

2024-03-04 22:05 UTC, JonathanWoollett-Light commented on ux2/Cargo.toml
> +emath = {version = "0.25", optional = true}
Nit:
```suggestion
emath = { version = "0.25", optional = true }
```

2024-03-04 22:12 UTC, closed without merging

2024-03-05 02:58 UTC, JonathanWoollett-Light commented
> Each? That'll be a ton of extra work, for something that'll be merged regardless, and create unnecessary conflicts in the changelog?

1 PR per area of change is best practices and helps speed up reviews. You don't need to edit the changelog.

2024-03-12 22:36 UTC, C0D3-M4513R commented
Okay. I made a pr for each thing.
Please note, that I cannot guarantee the correctness of some of the pr's, as some don't compile without their required pr's.